# Generated by Django 4.2.2 on 2023-07-18 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_klub', models.ImageField(default='csar_logo/logo_csar.jpeg', upload_to='klub_logo')),
                ('info', models.TextField(blank=True)),
                ('adresa', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('telefon', models.CharField(blank=True, max_length=255)),
                ('aktivni', models.BooleanField(default=True)),
                ('klub', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Zavod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_souteze', models.CharField(max_length=255, null=True)),
                ('datum_souteze', models.DateField(null=True)),
                ('prihlasky_do', models.DateField(null=True)),
                ('kategorie_deti', models.BooleanField(blank=True, default=False, null=True, verbose_name='Děti')),
                ('kategorie_zaci', models.BooleanField(blank=True, default=False, null=True, verbose_name='Žáci')),
                ('kategorie_junior', models.BooleanField(blank=True, default=False, null=True, verbose_name='Junior')),
                ('kategorie_c', models.BooleanField(blank=True, default=False, null=True, verbose_name='C')),
                ('kategorie_b', models.BooleanField(blank=True, default=False, null=True, verbose_name='B')),
                ('kategorie_a', models.BooleanField(blank=True, default=False, null=True, verbose_name='A')),
                ('kategorie_mdfd', models.BooleanField(blank=True, default=False, null=True, verbose_name='Malé Dívčí Formace Děti')),
                ('kategorie_mdfj', models.BooleanField(blank=True, default=False, null=True, verbose_name='Malé Dívčí Formace Junior')),
                ('kategorie_mdfs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Malé Dívčí Formace Senior')),
                ('kategorie_dfd', models.BooleanField(blank=True, default=False, null=True, verbose_name='Dívčí Formace Děti')),
                ('kategorie_dfj', models.BooleanField(blank=True, default=False, null=True, verbose_name='Dívčí Formace Junior')),
                ('kategorie_dfs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Dívčí Formace Senior')),
                ('kategorie_fj', models.BooleanField(blank=True, default=False, null=True, verbose_name='Párová Formace Junior')),
                ('kategorie_fs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Párová Formace Senior')),
                ('kategorie_dg', models.BooleanField(blank=True, default=False, null=True, verbose_name='Duo Girls')),
                ('kategorie_dl', models.BooleanField(blank=True, default=False, null=True, verbose_name='Duo Ladies')),
                ('kategorie_bw', models.BooleanField(blank=True, default=False, null=True, verbose_name='Boogie Woogie')),
                ('kategorie_fsm', models.BooleanField(blank=True, default=False, null=True, verbose_name='Formace smíšený věk')),
            ],
        ),
        migrations.CreateModel(
            name='Tanecnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_tanecnik', models.ImageField(default='foto_tanecnik/pic.jpg', upload_to='foto_tanecnik/profil_foto/', verbose_name='Fotografie')),
                ('jmeno', models.CharField(max_length=255, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=255, verbose_name='Příjmení')),
                ('datum_narozeni', models.DateField(verbose_name='Datum narození')),
                ('rodne_cislo', models.IntegerField(verbose_name='Rodné číslo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('adresa', models.TextField(blank=True, null=True, verbose_name='Adresa')),
                ('telefon', models.CharField(max_length=255, verbose_name='Telefonní číslo')),
                ('zdravotni_prohlidka', models.DateField(verbose_name='Zdravotní prohlídka DO ')),
                ('zdravotni_prohlidka_potvr', models.FileField(blank=True, null=True, upload_to='zdravotni_prohlidka/', verbose_name='Zdravotní prohlídka')),
                ('pas', models.FileField(blank=True, null=True, upload_to='kopie_pasu/', verbose_name='Kopie pasu')),
                ('doping', models.FileField(blank=True, null=True, upload_to='dopingove_prohlaseni/', verbose_name='Dopingove prohlašení')),
                ('registr_csar', models.BooleanField(default=False, null=True, verbose_name='Registrace csar')),
                ('datum_registrace', models.DateField(auto_now_add=True, null=True)),
                ('registrace_do', models.DateField(blank=True, default=web_app.models.platnost, null=True)),
                ('registr_zavodni_csar', models.BooleanField(default=False, null=True, verbose_name='Zavodni registrace')),
                ('datum_zavodni_registrace_csar', models.DateField(auto_now_add=True, null=True)),
                ('zavodni_registrace_do', models.DateField(blank=True, default=web_app.models.platnost, null=True)),
                ('registr_wrrc', models.BooleanField(default=False, null=True, verbose_name='Registrace wrrc')),
                ('datum_registrace_wrrc', models.DateField(auto_now_add=True, null=True)),
                ('registrace_wrrc_do', models.DateField(blank=True, default=web_app.models.platnost, null=True)),
                ('tanecnik', models.BooleanField(blank=True, default=False, null=True, verbose_name='Tanečník')),
                ('trener', models.BooleanField(blank=True, default=False, null=True, verbose_name='Trenér')),
                ('porotce', models.BooleanField(blank=True, default=False, null=True, verbose_name='Porotce')),
                ('odborny_dozor', models.BooleanField(blank=True, default=False, null=True, verbose_name='Odborný dozor')),
                ('klub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tanecni_jednotka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_tanecni_jednotky', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jméno taneční jednotky')),
                ('kategorie', models.CharField(choices=[('Děti', 'Kategorie Děti'), ('Žáci', 'Kategorie Žáci'), ('Junior', 'Kategorie Junior'), ('C', 'Kategorie C'), ('B', 'Kategorie B'), ('A', 'Kategorie A'), ('MDFD', 'Malá Dívčí Formace Děti'), ('MDFJ', 'Malá Dívčí Formace Junior'), ('MDFS', 'Malá Dívčí Formace Senior'), ('DFD', 'Dívčí Formace Děti'), ('DFJ', 'Dívčí Formace Junior'), ('DFS', 'Dívčí Formace Senior'), ('PFJ', 'Párová Formace Junior'), ('PFS', 'Párová Formace Senior'), ('DG', 'Duo Girls'), ('DL', 'Duo Ladies'), ('BW', 'Boogie Woogie'), ('FSm', 'Formace smíšený věk')], max_length=128, null=True, verbose_name='Kategorie')),
                ('klub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.profil')),
                ('tanecnici', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.tanecnik')),
            ],
        ),
        migrations.CreateModel(
            name='Prihlaska_zavod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(max_length=255, verbose_name='Kategorie')),
                ('tanecni_jednotka_jmeno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jméno taneční jednotky')),
                ('platba', models.BooleanField(default=False, verbose_name='Platba')),
                ('datum_prihlaseni', models.DateTimeField(auto_now_add=True, null=True)),
                ('hudba', models.FileField(blank=True, upload_to='zavodni_hudba', verbose_name='Závodní hudba')),
                ('klub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clen_klubu', to=settings.AUTH_USER_MODEL)),
                ('tanecni_jednotka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.tanecni_jednotka')),
                ('zavod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prihlaseni', to='web_app.zavod')),
            ],
        ),
    ]
