# Generated by Django 4.2.1 on 2023-08-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='rodne_cislo',
            field=models.IntegerField(unique=True, verbose_name='Rodné číslo'),
        ),
    ]
