# Generated by Django 4.2.2 on 2023-06-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='is_klub',
            new_name='id_klub',
        ),
        migrations.AddField(
            model_name='profil',
            name='telefon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
