# Generated by Django 4.2.2 on 2023-06-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_rename_is_klub_profil_id_klub_profil_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='telefon',
            field=models.IntegerField(blank=True),
        ),
    ]
