# Generated by Django 4.2.2 on 2023-06-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_profil_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='telefon',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
