# Generated by Django 4.2.2 on 2023-06-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0007_profil_telefon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='aktivni',
            field=models.BooleanField(default=True),
        ),
    ]
