# Generated by Django 4.2.2 on 2023-06-27 07:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0008_profil_aktivni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tanecnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_tanecnik', models.ImageField(default='foto_tanecnik/profile_pic.jpg', upload_to='foto_tanecnik', verbose_name='Fotografie')),
                ('jmeno', models.CharField(max_length=255, verbose_name='Jméno')),
                ('prijmeni', models.CharField(max_length=255, verbose_name='Příjmení')),
                ('datum_narozeni', models.DateField(verbose_name='Datum narození')),
                ('rodne_cislo', models.IntegerField(verbose_name='Rodné číslo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telefon', models.CharField(max_length=255, verbose_name='Telefonní číslo')),
                ('zdravotni_prohlidka', models.DateField(verbose_name='Zdravotní prohlídka DO: ')),
                ('zdravotni_prohlidka_potvr', models.ImageField(upload_to='', verbose_name='Zdravotní prohlídka')),
                ('pas', models.FileField(upload_to='', verbose_name='Kopie pasu')),
                ('doping', models.FileField(upload_to='', verbose_name='Dopingove prohlašení')),
                ('datum_registrace', models.DateField(verbose_name=datetime.date(2023, 6, 27))),
                ('registrace_do', models.DateField(verbose_name=2024)),
                ('registr_wrrc', models.BooleanField(default=False)),
                ('registr_csar', models.BooleanField(default=False)),
                ('registr_zavodni_csar', models.BooleanField(default=False)),
                ('klub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
