# Generated by Django 4.2.2 on 2023-06-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0009_tanecnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='registr_csar',
            field=models.BooleanField(default=False, verbose_name='Registrace csar'),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registr_wrrc',
            field=models.BooleanField(default=False, verbose_name='Registrace wrrc'),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registr_zavodni_csar',
            field=models.BooleanField(default=False, verbose_name='Zavodni registrace'),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_do',
            field=models.DateField(verbose_name=391),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zdravotni_prohlidka_potvr',
            field=models.FileField(upload_to='', verbose_name='Zdravotní prohlídka'),
        ),
    ]
