# Generated by Django 4.2.2 on 2023-06-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0010_alter_tanecnik_registr_csar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='doping',
            field=models.FileField(upload_to='dopingove_prohlaseni', verbose_name='Dopingove prohlašení'),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='foto_tanecnik',
            field=models.ImageField(default='profile_pic.jpg', upload_to='foto_tanecnik', verbose_name='Fotografie'),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='pas',
            field=models.FileField(upload_to='kopie_pasu', verbose_name='Kopie pasu'),
        ),
    ]
