# Generated by Django 4.2.2 on 2023-06-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0013_alter_tanecnik_foto_tanecnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='foto_tanecnik',
            field=models.ImageField(default='pic.jpg', upload_to='foto_tanecnik', verbose_name='Fotografie'),
        ),
    ]
