# Generated by Django 4.2.2 on 2023-06-28 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0018_tanecnik_reg_try_alter_tanecnik_datum_registrace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='doping',
            field=models.FileField(blank=True, upload_to='dopingove_prohlaseni', verbose_name='Dopingove prohlašení'),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='pas',
            field=models.FileField(blank=True, upload_to='kopie_pasu', verbose_name='Kopie pasu'),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='reg_try',
            field=models.DateField(null=True, verbose_name=datetime.datetime(2023, 6, 28, 13, 12, 41, 554379)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zdravotni_prohlidka_potvr',
            field=models.FileField(blank=True, upload_to='zdravotni_prohlidka', verbose_name='Zdravotní prohlídka'),
        ),
    ]
