# Generated by Django 4.2.2 on 2023-06-28 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0019_alter_tanecnik_doping_alter_tanecnik_pas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tanecnik',
            name='reg_try',
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_registrace',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 6, 28, 13, 30, 52, 110102)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_registrace_wrrc',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 6, 28, 13, 30, 52, 110135)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_zavodni_registrace_csar',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.datetime(2023, 6, 28, 13, 30, 52, 110122)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_do',
            field=models.DateField(blank=True, null=True, verbose_name=392),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_wrrc_do',
            field=models.DateField(blank=True, null=True, verbose_name=392),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zavodni_registrace_do',
            field=models.DateField(blank=True, null=True, verbose_name=392),
        ),
    ]
