# Generated by Django 4.2.2 on 2023-06-28 13:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0023_alter_tanecnik_registrace_do_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_wrrc_do',
            field=models.DateField(blank=True, default=392, null=True, verbose_name=datetime.date(2023, 6, 28)),
        ),
    ]
