# Generated by Django 4.2.2 on 2023-06-28 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0024_alter_tanecnik_registrace_wrrc_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_registrace',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.date(2023, 6, 28)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_zavodni_registrace_csar',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.date(2023, 6, 28)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_wrrc_do',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 6, 28)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zavodni_registrace_do',
            field=models.DateTimeField(blank=True, null=True, verbose_name=datetime.date(2023, 6, 28)),
        ),
    ]
