# Generated by Django 4.2.2 on 2023-06-28 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0025_alter_tanecnik_datum_registrace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_registrace',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 6, 28)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_zavodni_registrace_csar',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 6, 28)),
        ),
    ]
