# Generated by Django 4.2.2 on 2023-07-04 08:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0027_alter_tanecnik_registrace_do_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soutez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_souteze', models.CharField(max_length=255, null=True)),
                ('datum_souteze', models.DateField()),
                ('kategorie_deti', models.BooleanField(blank=True, default=False, null=True, verbose_name='Děti')),
                ('kategorie_zaci', models.BooleanField(blank=True, default=False, null=True, verbose_name='Žáci')),
                ('kategorie_junior', models.BooleanField(blank=True, default=False, null=True, verbose_name='Junior')),
                ('kategorie_c', models.BooleanField(blank=True, default=False, null=True, verbose_name='C')),
                ('kategorie_b', models.BooleanField(blank=True, default=False, null=True, verbose_name='B')),
                ('kategorie_a', models.BooleanField(blank=True, default=False, null=True, verbose_name='A')),
                ('kategorie_mdfd', models.BooleanField(blank=True, default=False, null=True, verbose_name='Malé Dívčí Formace Děti')),
                ('kategorie_mdfj', models.BooleanField(blank=True, default=False, null=True, verbose_name='Malé Dívčí Formace Junior')),
                ('kategorie_mdfs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Malé Dívčí Formace Senior')),
                ('kategorie_dfd', models.BooleanField(blank=True, default=False, null=True, verbose_name='Dívčí Formace Děti')),
                ('kategorie_dfj', models.BooleanField(blank=True, default=False, null=True, verbose_name='Dívčí Formace Junior')),
                ('kategorie_dfs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Dívčí Formace Senior')),
                ('kategorie_fj', models.BooleanField(blank=True, default=False, null=True, verbose_name='Párová Formace Junior')),
                ('kategorie_fs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Párová Formace Senior')),
                ('kategorie_dg', models.BooleanField(blank=True, default=False, null=True, verbose_name='Duo Girls')),
                ('kategorie_dl', models.BooleanField(blank=True, default=False, null=True, verbose_name='Duo Ladies')),
            ],
        ),
        migrations.AddField(
            model_name='tanecnik',
            name='adresa',
            field=models.TextField(blank=True, null=True, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='klub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_registrace',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 7, 4)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_registrace_wrrc',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 7, 4)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_zavodni_registrace_csar',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 7, 4)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='klub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_do',
            field=models.DateField(blank=True, null=True, verbose_name=368),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_wrrc_do',
            field=models.DateField(blank=True, null=True, verbose_name=368),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zavodni_registrace_do',
            field=models.DateField(blank=True, null=True, verbose_name=368),
        ),
        migrations.CreateModel(
            name='Tanecni_jednotka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_tanecnik1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik1', to='web_app.tanecnik')),
                ('jmeno_tanecnik10', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik10', to='web_app.tanecnik')),
                ('jmeno_tanecnik11', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik11', to='web_app.tanecnik')),
                ('jmeno_tanecnik12', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik12', to='web_app.tanecnik')),
                ('jmeno_tanecnik13', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik13', to='web_app.tanecnik')),
                ('jmeno_tanecnik14', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik14', to='web_app.tanecnik')),
                ('jmeno_tanecnik2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik2', to='web_app.tanecnik')),
                ('jmeno_tanecnik3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik3', to='web_app.tanecnik')),
                ('jmeno_tanecnik4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik4', to='web_app.tanecnik')),
                ('jmeno_tanecnik5', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik5', to='web_app.tanecnik')),
                ('jmeno_tanecnik6', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik6', to='web_app.tanecnik')),
                ('jmeno_tanecnik7', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik7', to='web_app.tanecnik')),
                ('jmeno_tanecnik8', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik8', to='web_app.tanecnik')),
                ('jmeno_tanecnik9', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik9', to='web_app.tanecnik')),
                ('klub', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prihlaska_soutez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(max_length=255, verbose_name='Kategorie')),
                ('platba', models.BooleanField(default=False, verbose_name='Platba')),
                ('datum_prihlaseni', models.DateTimeField(auto_now_add=True, null=True)),
                ('hudba', models.FileField(blank=True, upload_to='zavodni_hudba', verbose_name='Závodní hudba')),
                ('soutez', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.soutez')),
                ('tanecni_jednotka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.tanecni_jednotka')),
            ],
        ),
    ]
