# Generated by Django 4.2.1 on 2023-07-04 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0028_soutez_tanecnik_adresa_alter_profil_klub_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zavod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno_souteze', models.CharField(max_length=255, null=True)),
                ('datum_souteze', models.DateField(null=True)),
                ('prihlasky_do', models.DateField(null=True)),
                ('kategorie_deti', models.BooleanField(blank=True, default=False, null=True, verbose_name='Děti')),
                ('kategorie_zaci', models.BooleanField(blank=True, default=False, null=True, verbose_name='Žáci')),
                ('kategorie_junior', models.BooleanField(blank=True, default=False, null=True, verbose_name='Junior')),
                ('kategorie_c', models.BooleanField(blank=True, default=False, null=True, verbose_name='C')),
                ('kategorie_b', models.BooleanField(blank=True, default=False, null=True, verbose_name='B')),
                ('kategorie_a', models.BooleanField(blank=True, default=False, null=True, verbose_name='A')),
                ('kategorie_mdfd', models.BooleanField(blank=True, default=False, null=True, verbose_name='Malé Dívčí Formace Děti')),
                ('kategorie_mdfj', models.BooleanField(blank=True, default=False, null=True, verbose_name='Malé Dívčí Formace Junior')),
                ('kategorie_mdfs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Malé Dívčí Formace Senior')),
                ('kategorie_dfd', models.BooleanField(blank=True, default=False, null=True, verbose_name='Dívčí Formace Děti')),
                ('kategorie_dfj', models.BooleanField(blank=True, default=False, null=True, verbose_name='Dívčí Formace Junior')),
                ('kategorie_dfs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Dívčí Formace Senior')),
                ('kategorie_fj', models.BooleanField(blank=True, default=False, null=True, verbose_name='Párová Formace Junior')),
                ('kategorie_fs', models.BooleanField(blank=True, default=False, null=True, verbose_name='Párová Formace Senior')),
                ('kategorie_dg', models.BooleanField(blank=True, default=False, null=True, verbose_name='Duo Girls')),
                ('kategorie_dl', models.BooleanField(blank=True, default=False, null=True, verbose_name='Duo Ladies')),
            ],
        ),
        migrations.AlterField(
            model_name='prihlaska_soutez',
            name='soutez',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.zavod'),
        ),
        migrations.DeleteModel(
            name='Soutez',
        ),
    ]
