# Generated by Django 4.2.1 on 2023-07-04 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0029_zavod_alter_prihlaska_soutez_soutez_delete_soutez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik1', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik10', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik11',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik11', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik12',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik12', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik13',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik13', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik14',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik14', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik2', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik3', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik4', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik5', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik6', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik7', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik8', to='web_app.tanecnik'),
        ),
        migrations.AlterField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecnik9',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tanecnik9', to='web_app.tanecnik'),
        ),
    ]
