# Generated by Django 4.2.1 on 2023-07-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0030_alter_tanecni_jednotka_jmeno_tanecnik1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanecni_jednotka',
            name='jmeno_tanecni_jednotky',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Jméno taneční jednotky'),
        ),
    ]
