# Generated by Django 4.2.1 on 2023-07-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0031_tanecni_jednotka_jmeno_tanecni_jednotky'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prihlaska_zavod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategorie', models.CharField(max_length=255, verbose_name='Kategorie')),
                ('tanecni_jednotka_jmeno', models.CharField(blank=True, max_length=255, null=True, verbose_name='Jméno taneční jednotky')),
                ('platba', models.BooleanField(default=False, verbose_name='Platba')),
                ('datum_prihlaseni', models.DateTimeField(auto_now_add=True, null=True)),
                ('hudba', models.FileField(blank=True, upload_to='zavodni_hudba', verbose_name='Závodní hudba')),
                ('soutez', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.zavod')),
                ('tanecni_jednotka', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_app.tanecni_jednotka')),
            ],
        ),
        migrations.DeleteModel(
            name='Prihlaska_soutez',
        ),
    ]
