# Generated by Django 4.2.2 on 2023-07-05 09:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0033_remove_tanecnik_adresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prihlaska_zavod',
            name='soutez',
        ),
        migrations.AddField(
            model_name='prihlaska_zavod',
            name='zavod',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prihalseni', to='web_app.zavod'),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_registrace',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 7, 5)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_registrace_wrrc',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 7, 5)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_zavodni_registrace_csar',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 7, 5)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_do',
            field=models.DateField(blank=True, null=True, verbose_name=369),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_wrrc_do',
            field=models.DateField(blank=True, null=True, verbose_name=369),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zavodni_registrace_do',
            field=models.DateField(blank=True, null=True, verbose_name=369),
        ),
    ]
