# Generated by Django 4.2.2 on 2023-07-05 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0035_alter_prihlaska_zavod_zavod'),
    ]

    operations = [
        migrations.AddField(
            model_name='prihlaska_zavod',
            name='klub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clen_klubu', to=settings.AUTH_USER_MODEL),
        ),
    ]
