# Generated by Django 4.2.2 on 2023-07-07 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0036_prihlaska_zavod_klub'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanecnik',
            name='adresa',
            field=models.TextField(blank=True, null=True, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_registrace',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 7, 7)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_registrace_wrrc',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 7, 7)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='datum_zavodni_registrace_csar',
            field=models.DateField(blank=True, null=True, verbose_name=datetime.date(2023, 7, 7)),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_do',
            field=models.DateField(blank=True, null=True, verbose_name=371),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_wrrc_do',
            field=models.DateField(blank=True, null=True, verbose_name=371),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zavodni_registrace_do',
            field=models.DateField(blank=True, null=True, verbose_name=371),
        ),
    ]
