# Generated by Django 4.2.2 on 2023-07-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0037_tanecnik_adresa_alter_tanecnik_datum_registrace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='foto_tanecnik',
            field=models.ImageField(default='foto_tanecnik/pic.jpg', upload_to='foto_tanecnik/', verbose_name='Fotografie'),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zdravotni_prohlidka',
            field=models.DateField(verbose_name='Zdravotní prohlídka DO '),
        ),
    ]
