# Generated by Django 4.2.2 on 2023-07-07 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0039_alter_tanecnik_datum_registrace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_do',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_wrrc_do',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zavodni_registrace_do',
            field=models.DateField(blank=True, null=True),
        ),
    ]
