# Generated by Django 4.2.2 on 2023-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0040_alter_tanecnik_registrace_do_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='foto_tanecnik',
            field=models.ImageField(default='foto_tanecnik/pic.jpg', upload_to='foto_tanecnik', verbose_name='Fotografie'),
        ),
    ]
