# Generated by Django 4.2.1 on 2023-07-08 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0045_alter_tanecnik_registrace_wrrc_do_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='doping',
            field=models.FileField(upload_to='dopingove_prohlaseni', verbose_name='Dopingove prohlašení'),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='pas',
            field=models.FileField(upload_to='kopie_pasu', verbose_name='Kopie pasu'),
        ),
    ]
