# Generated by Django 4.2.1 on 2023-07-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0049_alter_tanecnik_doping_alter_tanecnik_pas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_do',
            field=models.DateField(blank=True, default=2024, null=True),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_wrrc_do',
            field=models.DateField(blank=True, default=2024, null=True),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zavodni_registrace_do',
            field=models.DateField(blank=True, default=2024, null=True),
        ),
    ]
