# Generated by Django 4.2.1 on 2023-07-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0051_alter_tanecnik_registrace_do_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_do',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_wrrc_do',
            field=models.DateField(blank=True, null=True, verbose_name=372),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zavodni_registrace_do',
            field=models.DateField(blank=True, null=True),
        ),
    ]
