# Generated by Django 4.2.1 on 2023-07-08 09:27

from django.db import migrations, models
import web_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0053_alter_tanecni_jednotka_jmeno_tanecnik13_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_do',
            field=models.DateField(blank=True, default=web_app.models.platnost, null=True),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='registrace_wrrc_do',
            field=models.DateField(blank=True, default=web_app.models.platnost, null=True),
        ),
        migrations.AlterField(
            model_name='tanecnik',
            name='zavodni_registrace_do',
            field=models.DateField(blank=True, default=web_app.models.platnost, null=True),
        ),
    ]
