# Generated by Django 4.2.2 on 2023-07-13 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0056_tanecni_jednotka_kategorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profil',
            old_name='adressa',
            new_name='adresa',
        ),
    ]
