# Generated by Django 4.2.2 on 2023-07-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0058_alter_tanecni_jednotka_kategorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tanecnik',
            name='odborny_dozor',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Odborný dozor'),
        ),
        migrations.AddField(
            model_name='tanecnik',
            name='porotce',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Porotce'),
        ),
        migrations.AddField(
            model_name='tanecnik',
            name='trener',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Trenér'),
        ),
        migrations.AddField(
            model_name='zavod',
            name='kategorie_bw',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Boogie Woogie'),
        ),
        migrations.AddField(
            model_name='zavod',
            name='kategorie_fsm',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Formace smíšený věk'),
        ),
    ]
